export const WEB_HOST_SHOW_DETAIL = "WEB_HOST_SHOW_DETAIL";
export const WEB_HOST_SHOW_DETAIL_SUCCESSFUL = "WEB_HOST_SHOW_DETAIL_SUCCESSFUL";
export const WEB_HOST_SHOW_DETAIL_FAILED = "WEB_HOST_SHOW_DETAIL_FAILED";

export const WEB_HOST_DROPDOWN = "WEB_HOST_DROPDOWN";
export const WEB_HOST_DROPDOWN_SUCCESSFUL = "WEB_HOST_DROPDOWN_SUCCESSFUL";
export const WEB_HOST_DROPDOWN_FAILED = "WEB_HOST_DROPDOWN_FAILED";

export const RESET_WEB_HOST_SHOW_DETAIL_FLAG = "RESET_WEB_HOST_SHOW_DETAIL_FLAG";
