export const PERFORMANCE_SHOW_DETAIL = "PERFORMANCE_SHOW_DETAIL";
export const PERFORMANCE_SHOW_DETAIL_SUCCESSFUL = "PERFORMANCE_SHOW_DETAIL_SUCCESSFUL";
export const PERFORMANCE_SHOW_DETAIL_FAILED = "PERFORMANCE_SHOW_DETAIL_FAILED";
export const RESET_PERFORMANCE_SHOW_DETAIL_FLAG = "RESET_PERFORMANCE_SHOW_DETAIL_FLAG";
