export const TECHNOLOGY_LIST = "TECHNOLOGY_LIST";
export const TECHNOLOGY_LIST_SUCCESSFUL = "TECHNOLOGY_LIST_SUCCESSFUL";
export const TECHNOLOGY_LIST_FAILED = "TECHNOLOGY_LIST_FAILED";
export const RESET_TECHNOLOGY_LIST_FLAG = "RESET_TECHNOLOGY_LIST_FLAG";
export const REFRESH_TECHNOLOGY_LIST_FLAG = "REFRESH_TECHNOLOGY_LIST_FLAG";
