export const SAVE_DEFAULT_PLAN = "SAVE_DEFAULT_PLAN";
export const SAVE_DEFAULT_PLAN_SUCCESSFUL = "SAVE_DEFAULT_PLAN_SUCCESSFUL";
export const SAVE_DEFAULT_PLAN_FAILED = "SAVE_DEFAULT_PLAN_FAILED";

export const DELETE_DEFAULT_PLAN = "DELETE_DEFAULT_PLAN";
export const DELETE_DEFAULT_PLAN_SUCCESSFUL = "DELETE_DEFAULT_PLAN_SUCCESSFUL";
export const DELETE_DEFAULT_PLAN_FAILED = "DELETE_DEFAULT_PLAN_FAILED";

export const RESET_SAVE_DEFAULT_PLAN_FLAG = "RESET_SAVE_DEFAULT_PLAN_FLAG";
