export const SAVE_PROJECT = "SAVE_PROJECT";
export const SAVE_PROJECT_SUCCESSFUL = "SAVE_PROJECT_SUCCESSFUL";
export const SAVE_PROJECT_FAILED = "SAVE_PROJECT_FAILED";

export const DELETE_PROJECT = "DELETE_PROJECT";
export const DELETE_PROJECT_SUCCESSFUL = "DELETE_PROJECT_SUCCESSFUL";
export const DELETE_PROJECT_FAILED = "DELETE_PROJECT_FAILED";

export const RESET_SAVE_PROJECT_FLAG = "RESET_SAVE_PROJECT_FLAG";
