export const CREATE_SKILLSET = "CREATE_SKILLSET";
export const CREATE_SKILLSET_SUCCESSFUL = "CREATE_SKILLSET_SUCCESSFUL";
export const CREATE_SKILLSET_FAILED = "CREATE_SKILLSET_FAILED";

export const DELETE_SKILLSET = "DELETE_SKILLSET";
export const DELETE_SKILLSET_SUCCESSFUL = "DELETE_SKILLSET_SUCCESSFUL";
export const DELETE_SKILLSET_FAILED = "DELETE_SKILLSET_FAILED";

export const RESET_CREATE_SKILLSET_FLAG = "RESET_CREATE_SKILLSET_FLAG";
