export const DEFAULT_PLAN_LIST = "DEFAULT_PLAN_LIST";
export const DEFAULT_PLAN_LIST_SUCCESSFUL = "DEFAULT_PLAN_LIST_SUCCESSFUL";
export const DEFAULT_PLAN_LIST_FAILED = "DEFAULT_PLAN_LIST_FAILED";
export const RESET_DEFAULT_PLAN_LIST_FLAG = "RESET_DEFAULT_PLAN_LIST_FLAG";
export const REFRESH_DEFAULT_PLAN_LIST_FLAG = "REFRESH_DEFAULT_PLAN_LIST_FLAG";
