export const SKILLSET_LIST = "SKILLSET_LIST";
export const SKILLSET_LIST_SUCCESSFUL = "SKILLSET_LIST_SUCCESSFUL";
export const SKILLSET_LIST_FAILED = "SKILLSET_LIST_FAILED";
export const RESET_SKILLSET_LIST_FLAG = "RESET_SKILLSET_LIST_FLAG";
export const REFRESH_SKILLSET_LIST_FLAG = "REFRESH_SKILLSET_LIST_FLAG";
