export const PROJECT_SHOW_DETAIL = "PROJECT_SHOW_DETAIL";
export const PROJECT_SHOW_DETAIL_SUCCESSFUL = "PROJECT_SHOW_DETAIL_SUCCESSFUL";
export const PROJECT_SHOW_DETAIL_FAILED = "PROJECT_SHOW_DETAIL_FAILED";
export const RESET_PROJECT_SHOW_DETAIL_FLAG = "RESET_PROJECT_SHOW_DETAIL_FLAG";
