export const PERFORMANCE_LIST = "PERFORMANCE_LIST";
export const PERFORMANCE_LIST_SUCCESSFUL = "PERFORMANCE_LIST_SUCCESSFUL";
export const PERFORMANCE_LIST_FAILED = "PERFORMANCE_LIST_FAILED";
export const RESET_PERFORMANCE_LIST_FLAG = "RESET_PERFORMANCE_LIST_FLAG";
export const REFRESH_PERFORMANCE_LIST_FLAG = "REFRESH_PERFORMANCE_LIST_FLAG";
