export const SKILLSET_SHOW_DETAIL = "SKILLSET_SHOW_DETAIL";
export const SKILLSET_SHOW_DETAIL_SUCCESSFUL = "SKILLSET_SHOW_DETAIL_SUCCESSFUL";
export const SKILLSET_SHOW_DETAIL_FAILED = "SKILLSET_SHOW_DETAIL_FAILED";
export const RESET_SKILLSET_SHOW_DETAIL_FLAG = "RESET_SKILLSET_SHOW_DETAIL_FLAG";
