export const PERFORMANCE_TYPE_LIST = "PERFORMANCE_TYPE_LIST";
export const PERFORMANCE_TYPE_LIST_SUCCESSFUL = "PERFORMANCE_TYPE_LIST_SUCCESSFUL";
export const PERFORMANCE_TYPE_LIST_FAILED = "PERFORMANCE_TYPE_LIST_FAILED";
export const RESET_PERFORMANCE_TYPE_LIST_FLAG = "RESET_PERFORMANCE_TYPE_LIST_FLAG";
export const REFRESH_PERFORMANCE_TYPE_LIST_FLAG = "REFRESH_PERFORMANCE_TYPE_LIST_FLAG";
