export const WEB_HOST_LIST = "WEB_HOST_LIST";
export const WEB_HOST_LIST_SUCCESSFUL = "WEB_HOST_LIST_SUCCESSFUL";
export const WEB_HOST_LIST_FAILED = "WEB_HOST_LIST_FAILED";
export const RESET_WEB_HOST_LIST_FLAG = "RESET_WEB_HOST_LIST_FLAG";
export const REFRESH_WEB_HOST_LIST_FLAG = "REFRESH_WEB_HOST_LIST_FLAG";
