export const SAVE_PERFORMANCE = "SAVE_PERFORMANCE";
export const SAVE_PERFORMANCE_SUCCESSFUL = "SAVE_PERFORMANCE_SUCCESSFUL";
export const SAVE_PERFORMANCE_FAILED = "SAVE_PERFORMANCE_FAILED";

export const DELETE_PERFORMANCE = "DELETE_PERFORMANCE";
export const DELETE_PERFORMANCE_SUCCESSFUL = "DELETE_PERFORMANCE_SUCCESSFUL";
export const DELETE_PERFORMANCE_FAILED = "DELETE_PERFORMANCE_FAILED";

export const RESET_SAVE_PERFORMANCE_FLAG = "RESET_SAVE_PERFORMANCE_FLAG";
