export const SAVE_WEB_HOST = "SAVE_WEB_HOST";
export const SAVE_WEB_HOST_SUCCESSFUL = "SAVE_WEB_HOST_SUCCESSFUL";
export const SAVE_WEB_HOST_FAILED = "SAVE_WEB_HOST_FAILED";

export const DELETE_WEB_HOST = "DELETE_WEB_HOST";
export const DELETE_WEB_HOST_SUCCESSFUL = "DELETE_WEB_HOST_SUCCESSFUL";
export const DELETE_WEB_HOST_FAILED = "DELETE_WEB_HOST_FAILED";

export const RESET_SAVE_WEB_HOST_FLAG = "RESET_SAVE_WEB_HOST_FLAG";
