export const SAVE_PERFORMANCE_TYPE = "SAVE_PERFORMANCE_TYPE";
export const SAVE_PERFORMANCE_TYPE_SUCCESSFUL = "SAVE_PERFORMANCE_TYPE_SUCCESSFUL";
export const SAVE_PERFORMANCE_TYPE_FAILED = "SAVE_PERFORMANCE_TYPE_FAILED";

export const DELETE_PERFORMANCE_TYPE = "DELETE_PERFORMANCE_TYPE";
export const DELETE_PERFORMANCE_TYPE_SUCCESSFUL = "DELETE_PERFORMANCE_TYPE_SUCCESSFUL";
export const DELETE_PERFORMANCE_TYPE_FAILED = "DELETE_PERFORMANCE_TYPE_FAILED";

export const RESET_SAVE_PERFORMANCE_TYPE_FLAG = "RESET_SAVE_PERFORMANCE_TYPE_FLAG";
