export const PROJECT_LIST = "PROJECT_LIST";
export const PROJECT_LIST_SUCCESSFUL = "PROJECT_LIST_SUCCESSFUL";
export const PROJECT_LIST_FAILED = "PROJECT_LIST_FAILED";
export const RESET_PROJECT_LIST_FLAG = "RESET_PROJECT_LIST_FLAG";
export const REFRESH_PROJECT_LIST_FLAG = "REFRESH_PROJECT_LIST_FLAG";
