export const DEFAULT_PLAN_SHOW_DETAIL = "DEFAULT_PLAN_SHOW_DETAIL";
export const DEFAULT_PLAN_SHOW_DETAIL_SUCCESSFUL = "DEFAULT_PLAN_SHOW_DETAIL_SUCCESSFUL";
export const DEFAULT_PLAN_SHOW_DETAIL_FAILED = "DEFAULT_PLAN_SHOW_DETAIL_FAILED";
export const RESET_DEFAULT_PLAN_SHOW_DETAIL_FLAG = "RESET_DEFAULT_PLAN_SHOW_DETAIL_FLAG";
