export const CREATE_TECHNOLOGY = "CREATE_TECHNOLOGY";
export const CREATE_TECHNOLOGY_SUCCESSFUL = "CREATE_TECHNOLOGY_SUCCESSFUL";
export const CREATE_TECHNOLOGY_FAILED = "CREATE_TECHNOLOGY_FAILED";

export const DELETE_TECHNOLOGY = "DELETE_TECHNOLOGY";
export const DELETE_TECHNOLOGY_SUCCESSFUL = "DELETE_TECHNOLOGY_SUCCESSFUL";
export const DELETE_TECHNOLOGY_FAILED = "DELETE_TECHNOLOGY_FAILED";

export const RESET_CREATE_TECHNOLOGY_FLAG = "RESET_CREATE_TECHNOLOGY_FLAG";
