export const TECHNOLOGY_SHOW_DETAIL = "TECHNOLOGY_SHOW_DETAIL";
export const TECHNOLOGY_SHOW_DETAIL_SUCCESSFUL = "TECHNOLOGY_SHOW_DETAIL_SUCCESSFUL";
export const TECHNOLOGY_SHOW_DETAIL_FAILED = "TECHNOLOGY_SHOW_DETAIL_FAILED";
export const RESET_TECHNOLOGY_SHOW_DETAIL_FLAG = "RESET_TECHNOLOGY_SHOW_DETAIL_FLAG";
